language: ruby
rvm: 2.5.1

branches:
  only:
  - /.*/

cache: bundler

services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - bundle exec rake db:migrate RACK_ENV=test
script:
  - bundle exec rspec