development:
  adapter: postgresql
  database: micro_learning2


test:
  adapter: postgresql
  database: test

production:
  adapter: postgresql
  database: <%= ENV["DB_NAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>
  host: <%= ENV["DB_HOST"]%>
  user: <%= ENV["DB_USER"]%>
  
